languageCode = "en-us"
baseURL = ""
title = "WordBrewery Support and FAQ"
theme = "hugo-material-docs"
googleAnalytics = "UA-38165959-2"
relativeURLs = true
canonifyURLs = false
metaDataFormat = "toml"
config = "config.toml"
enableRobotsTXT = true
logFile = "log.txt"
newContentEditor = "emacs"
verbose = true
verboseLog = true
watch = true
staticdir = "static"

[params]
    author = "WordBrewery"
    description = "Support for language learners who want to get the most out of WordBrewery"
    logo = "/images/wordbrewery-logo-small.jpg"
    favicon = "https://wordbrewery.com/resources/images/favicon/favicon.ico"
    disableSitemap = false
    disable404 = true
        
    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/WordBrewery/wordbrewery-support/"
    permalinks = "/:section/:slug"
     # Custom assets
    custom_css = ["stylesheets/styles.css"]
    custom_js  = []

   [params.palette]
     primary = "yellow" # Actually WB gold (#EBB331)
     accent  = "teal" # Actually WB blue (#437C90)

   [params.font]
     text = "Work Sans"

[social]
    facebook      = "https://facebook.com/wordbrewery"
    googleplus    = "https://plus.google.com/+WordBreweryLanguages"
    tumblr        = "https://wordbrewery.tumblr.com"
    twitter       = "wordbrewery" # Intentionally shortened
    linkedin      = "https://www.linkedin.com/company/wordbrewery"
    stackoverflow = "http://stackoverflow.com/users/5083726/wordbrewery"
    #github        = "https://github.com/wordbrewery"
    youtube       = "https://youtube.com/wordbrewerylanguages"
    pinterest     = "https://www.pinterest.com/wordbrewery/"
    email         = "admin@wordbrewery.com"    


[[menu.main]]
       name = "WordBrewery Support and FAQ"
       url = "/"
       weight = 1

[[menu.main]]
       name   = "About WordBrewery"
       url    = "about/"
       weight = 10

[[menu.main]]
       name   = "Troubleshooting"
       url    = "troubleshooting/"
       weight = 90

[[menu.main]]
       name   = "Join WordBrewery"
       url    = "https://wordbrewery.com/subscriptions"
       weight = 0

[[menu.main]]
       name   = "Legal and Privacy"
       url = "https://wordbrewery.com/terms"
       weight = 99

[blackfriday]
       smartypants	= true
       fractions = true
       smartDashes = true
       plainIDAnchors = true
