
[params]

    # permalink = "#"

    custom_css = ["stylesheets/styles.css"]

    [params.palette]
        primary = "gold" # Actually WB gold
        accent  = "teal" # Actually WB blue

    [params.font]
        text = "Work Sans"
        code = "Ubuntu Mono"

# Menu
SectionPagesMenu = "main"

        [[menu.main]]
                name = "WordBrewery Support and FAQ"
                weight = 0
                url = "/"

        [[menu.main]]
                name = "About WordBrewery"
                weight = 10
                url = "about/"
        # [[menu.main]]
        #         name = "Features, Content, and Tech"
        #         weight = 20
        #         url = "features/"
        # [[menu.main]]
        #        name = "Research and Testimonials"
        #        weight = 30
        #        url = "research/"
        # [[menu.main]]
        #        name = "Social Media and Contact Info"
        #        weight = 40
        #        url = "contact/"
        # [[menu.main]]
        #         name = "Pricing and Subscriptions"
        #         weight = 50
        #         url = "subscriptions/"
        # [[menu.main]]
        #         name = "Your WordBrewery Account"
        #         weight = 60
        #         url = "account/"
        [[menu.main]]
                name = "Troubleshooting"
                weight = 90
                url = "troubleshooting/"

        [[menu.main]]
                name = "Legal and Privacy"
                weight = 99
                url = "https://wordbrewery.com/terms"


# HUGO VARIABLES

archetypeDir = "archetypes"
buildDrafts = false
buildFuture = false
buildExpired = false
config = "config.toml"
contentDir = "content"
dataDir = "data"
defaultExtension = "html"
defaultLayout = "single"
defaultContentLanguage = "en"
disableLiveReload = false
disableRSS = false
disableSitemap = false
enableRobotsTXT = true
disable404 = false
editor = "emacs"
enableEmoji = false
logFile = ".hugolog"
newContentEditor = "emacs"
layoutDir = "layouts"
metaDataFormat = "toml"
paginate = 1
paginatePath = "page"
watch = true
pluralizeListTitles = true
preserveTaxonomyNames = true
publishDir = "public"
pygmentsStyle = "monokai"
rssLimit = 15
sitemap="sitemap.xml"
hasCJKLanguage = true
verbose = true
staticDir = "static"
themesDir = "themes"
verboseLog = true
uglyURLs = false
disablePathToLower = false

# The below example will disable all page types and will render nothing.
# disableKinds = ["page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

# [params.permalinks]
#     pages="/:categories/:title.html"
#     posts="/:categories/:title.html"


# Styling

  custom_css = ["stylesheets/styles.css"]

  # Use custom.css for your custom styling
  style = "default"
  description = "Support and FAQ page to help language learners get the most out of WordBrewery."
  copyright = "&copy;2017 WordBrewery"
  sidebarAbout = [
    "WordBrewery Support and FAQ",
     ]

  dateFormat = "2 January 2006"

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "admin@wordbrewery.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "https://wordbrewery.com/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Email WordBrewery"
  url = "mailto:admin@wordbrewery.com"

  [params.social]
  facebook      = "https://facebook.com/wordbrewery"
  googleplus    = "https://plus.google.com/+WordBreweryLanguages"
  email         = "admin@wordbrewery.com"
  tumblr        = "https://wordbrewery.tumblr.com"
  twitter       = "wordbrewery" # Intentionally shortened
  linkedin      = "https://www.linkedin.com/company/wordbrewery"
  stackoverflow = "http://stackoverflow.com/users/5083726/wordbrewery"
  instagram     = "https://www.instagram.com/wordbrewery/"
  github        = "https://github.com/wordbrewery"
  youtube       = "https://youtube.com/wordbrewerylanguages"
  pinterest     = "https://www.pinterest.com/wordbrewery/"


[blackfriday]
        smartypants	= true
        fractions = true
        smartDashes = true
        plainIDAnchors = true
