languageCode = "en-us"
baseurl = "https://wordbrewery.com/support/"
title = "WordBrewery Support and FAQ"
theme = "hugo-material-docs"
googleAnalytics = "UA-38165959-2"
relativeURLs = true
canonifyURLs = false
#markup = "mmark"
metadataformat = "toml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    author = "WordBrewery"
    description = "Support for language learners who want to get the most out of WordBrewery"
    logo = "/images/wordbrewery-logo-small.jpg"
    favicon = "https://wordbrewery.com/resources/images/favicon/favicon.ico"
    disableSitemap = false
    disable404 = true

       # Repository
       provider = "GitHub"
       repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

       version = "1.0.0"
       logo = "images/logo.png"
       favicon = ""

       permalink = "#"

       # Custom assets
       custom_css = []
       custom_js  = []

       # Syntax highlighting theme
       highlight_css  = ""

       [params.palette]
       primary = "red"
       accent  = "teal"

   [params.font]
       text = "Ubuntu"
       code = "Ubuntu Mono"


[social]
       twitter = ""
       github  = "digitalcraftsman"
       email   = "hello@email.com"


[[menu.main]]
       name   = "Material"
       url    = "/"
       weight = 0

[[menu.main]]
       name   = "Getting started"
       url    = "getting-started/"
       weight = 10

[[menu.main]]
       name   = "Adding content"
       url    = "adding-content/"
       weight = 20

[[menu.main]]
       name   = "Roadmap"
       url    = "roadmap/"
       weight = 30

[[menu.main]]
       name   = "License"
       url    = "license/"
       weight = 40


[blackfriday]
       smartypants	= true
       fractions = true
       smartDashes = true
       plainIDAnchors = true
